import React from 'react';
import cssStyle from './Disclaimer.module.scss';
const Disclaimer = () => {
    return (
        <div className={`${cssStyle.article} bg-dark text-light`}>
            <div className={`${cssStyle.title} text-danger`}>GODD FATHER OF SATTA KING</div>
            Sattaking Game Was Played Offline From Early 1970's.but There Comes The God Father Of Online Satta.in 2010 The Godfather Of Satta THE ONE AND ONLY TASIM KHAN Bring It On An Online Platform.due To Him Today Lakhs Of People Are Playing Online And Earn Money.he Brings Satta King Game To The Another Level.now Everyone Copies Him But The Real Credit Of Bringing Online Satta Is Totally To Tasim Khan.he Created The Satta-king Website.he Is The Godfather Of Online Satta King Game.!
            <div className={`${cssStyle.title} text-danger`}>THE WORD 'SATTA KING</div>
            Satta Is A Game Which Is Played In Different Parts Of The Country.in Satta Certain Amount Of Money Is Put On One Number And If That Number Opens The Satta King Player Wins The Money.satta Is Illegal In Our Country.the Satta King Players Play Satta At Their Own Risk Only.satta King Sites Provide You The Information Only For Entertainment Purpose.we Do Not Promote Satta,we Only Provide You The Results Which Are Provided To Us By The Owner Of The Different Companies.satta Can Be Very Harmful.satta Should Not Be Played As It Face A Huge Loss.
            <div className={`${cssStyle.title} text-danger`}>WWW.SATTA-KING.IN NO. 1 WEBSITE IN WORLD</div>
            When Satta Came Online There Was Only One Website Which Is Satta-king.in The Word Satta King Was Also Founded From This Website.all The Other Websites Copied The Satta King Website.but In The Market Satta-king Has Its Own Reputation.peoples Trust Blindly On Satta-king.in Website.even Khaiwals Only Trust The Result Which Is Provided By This Website.satta King Website Is Famous All Over The World And Is No.1.many Websites Come And Go But They Were Not Able To Take Place Of Satta-king.our Website Is No.1 From Starting Because We Do Not Mis Guide People..
            <div className={`${cssStyle.title} text-danger`}>POPULAR SATTA KING GAME</div>
            In Satta King There Are Lots Of Companies.every Company Has Its Own Result.but In Todays Market Here Are Some Games In Which You Can Invest And Trust Blindly Because These Are Very Popular And People Win Very Much Amount Of Money From Them.here Are Some Popular Satta King Games.dishawar, Delhi Darbar, Faridabad, Ghaziabad,taj,new Faridabad,delhi Noon,punjab Day,delhi Day And Punjab Special.every Company Has Its Own Policy And Rate.
            <div className={`${cssStyle.title} text-danger`}>HOW TO PLAY SATTA</div>
            Satta King Game Can Be Played Both Online And Offline.in Satta King Game There Are Number From 1 To 100.these Number Are Put In The Pot And One Number Is Taken Out From It.the Satta King Player Which Has Same Number Matched Wins The Amount Of Money.you Can Put Certain Amount Of Money On One Or More Numbers,if Your Number Is Matched With That Number Than You Will Get The 90 Times The Amount Of Money You Had Put On It.in This You Can Put Money On Single Digit Also Which Is Known As Andar Bahar.for Eg The Number Is 98.in This 9 Is Andar 8 Is Bahar.if You Want To Play Andar Bahar You Can Put Money On Single Digit.if Your Digit Matched Then You Will Get 9 Times The Money You Have Put On It.there Are Many Kinds By Which You Can Play Satta King Game.in This Game You Can Lose All Your Money In It.chances Of Winning In Satta Game Is Very Loss Because Company Only Opens Those Numbers Onto Which Less Money Is Put.company Put All The Numbers In Software And See Which Number Has Less Amount Of Money And Open That Number Only.so Be Very Careful While Playing Satta King Game.
            <div className={`${cssStyle.title} text-danger`}>HOW TO BETTING SATTA</div>
            You can play satta online and offline as well as in the area state where you live, there are agents of the company, to write your bet, who is known as Khaiwal, you go to them and by giving them money, you will get their number. Money has to be invested, he has to be told, suppose you have to put 100 rupees on number 22, then you have to tell them that put my money on number 22, you will put your money on the same number and give you a small slip in which you will have written On which number, how much money have you invested, now after that game on which you invested money, if the same number opens, then you will have to go to Khaiwal with the same slip, he will match the slip with his pass and pay you, the match will be done because because A duplicate slip is also with the Khaiwal, otherwise anyone can make a slip from his own and go to collect the payment.
            <div className={`${cssStyle.title} text-danger`}>JODI AND HARUF WHAT HAPPEN INSIDE OUTSIDE</div>
            Jodi means a single number from 1 to 100, you invest your money on any single number like suppose you put 500 rupees on number 22, it means you have invested money on a pair. Haruf means that if you put money on 5 haruf, then any number from 1 to 100 on which it is in 5 units, then your haruf will be considered as pass like understand 05 25 35 65 95 all of these 5 numbers are in units and If any of these numbers is opened then you will take money but there is a different rule in it like if you invest money on any pair, it opens then you will get 90 rupees of 1 rupee, same if you invest money in any haruf then you will get 1 rupee You will get only 9 rupees not 90 rupees because now the chances of opening your numbers have increased, the more risk you take in this betting game, the more profit you will get Inside out means as if you played Haruf and you invested your money in 5 Haruf, it is played in the same way as outside means Haruf only, just inside means you have to understand as if it was in 5 units in Haruf or Bahar like 05 25 15 95 in the same way 5 will be in tens in the same way 51 55 59 52 Now you see whatever 5 is in it is on the inside side it means 5 is open inside in this also you will get 90 of 1 rupee not 9 why that your chances of getting it too are very high
            <div className={`${cssStyle.title} text-danger`}>WHAT IS SATTA KING</div>
            Satta King Is A Satta Game Which Is Very Popular In India.as You Have Heard The Name Satta King Many Times From Your Friends,satta King Is Very Popular.satta King Game Is Played At Very High Stake In India.the Craze Among The People About The Satta King Game Is Increasing At A Very Fast Rate And People Are Getting Addicted To It.satta King Game Can Be Very Harmful As You Can Lose Your All Money In This Game.your Hard Earned Money Can Be Gone Within A Day In The Satta King Game.below Is The More Information Which We Will Give You About The Satta Game That You All Need To Be Know.we Will Tell You Where The Satta King Game Is Played And What Is The Technique By Which You Can Win Or Lose From The Satta King Game.we Sincerely Tell You To Read All The Rules And Regulations And Disclaimer Before Proceeding Further,it Will Help You To Know About The Game More.some Advantages And Disadvantages Will Be Told To You About The Satta King Game.satta King Game Is Very Popular So You Should Know Each And Everything About It
            <div className={`${cssStyle.title} text-danger`}>HOW CAN WE PLAY BETTING ONLINE?</div>
            As you all know, now we can do money transactions very easily with anyone at any time, as you have read above, you go to your Khaiwal to play betting, then add your numbers to him, whatever you need inside / outside. He also tells you to play, then he gives you the slip, this process we call to play offline betting, it has its own advantage and disadvantage too. How is Khaiwal, you do not want to come to pay, you are familiar with it, but you also have a risk in it, you got the bet written, Khaiwal gave you the slip, if that slip is lost from you, then Khaiwal can also refuse to pay you And the second risk is that sometimes you went to Khaiwal to write betting and at the same time there was a police raid, then you can also be arrested or you will believe that because according to the law of the Government of India, both playing betting and playing. It is a legal crime, for which you can be fined heavily and can be put in jail, now you have to play online. I also tell the advantages and disadvantages, as you have read upen, you know the work with which you get your bet written, but you do not know anyone in online because there is no one who comes to know about the online betting player. You can talk to him only through phone whats app sms, if he does not want to talk to you or does not want to pay you, even then you cannot do anything because you do not know anything about that gap, you do not even go to the police Otherwise you can get in trouble, this is its disadvantage, now also understand the advantages of online, whether you are at home or office or traveling, just need to have internet or calling in your phone, you can get your bet written from any place. also lives with you and if you are honest then you can also do your payment transactions very easily PAYTM PHONEPE GOOGLEPAY and there are many more facilities you can use anyone
            <div className={`${cssStyle.title} text-danger`}>WHERE IS SATTA PLAYED</div>
            Sattaking Game Is Mostly Played In Northern Part Of India.mainly In Punjab Up Delhi Haryana And Some Other Parts Also.it Is Not That Kind That Sattaking Is Played Only In Northern Part It Is Played All Over India As Well As In Other Countries Also.sattaking Offers You A Lot.one Can Play It Both Offline As Well As Online Medium
            <div className={`${cssStyle.title} text-danger`}>SATTA KING IS REAL?</div>
            There Are Lot Of Rumors In Market That Whether Satta King Game Is Real Or Fake.we Can Assure You That Satta-king Game Is 100% Real.those Who Say Sattaking Game Is Fake Are Fooling You.we Will Give You Further Clarification Regarding This.in Small Villages There Can Be Small Fraud.because In Satta King There Are Some Khaiwals Which Rest All The Satta In Their Pocket Only.they Do Not Send Those Satta To The Sattaking Company.when The Number Is Opened They Try To Fool The Satta Game Players.satta Is Real If You Play With The Good Peoples.you Can Invest Your Money In Satta King Game If You Can Guess The Confirmed Number Of The Upcoming Results.
        </div>
    );
};

export default Disclaimer;